### ISSUE TITLE
Support for USB OTG 

### ISSUE THREAD

**Issue by NehalkumarMaheshwari** [veniosg/Dir#132] opened 2020-09-24 17:56 UTC
Add support for USB OTG volumes either by using an integrated library, or preferably using the Storage Access Framework Android provides.

User can notify if any usb device is connected and disconnected and display files and folders from usb like google files do.

**Comment by veniosg** [comment] 2020-10-28 16:17
Closing as it is a dupe of https://github.com/veniosg/Dir/issues/31. Thanks for leaving a comment there 👍

**Closed by veniosg** 2020-10-28 16:17 UTC
